collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "pfbeautysalon.com" # does not include hostname
show_dir_listing    : false
